

services:
  backend:
    build: .
    container_name: be_assement-backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    depends_on:
      - mongo
    command: npm run dev   # use npm run start for production

  mongo:
    image: mongo:6
    container_name: be_assement-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: be_assement

volumes:
  mongo-data:
